language: java
install: true

os: linux
dist: trusty
jdk: oraclejdk8

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - ./gradlew build -Dorg.gradle.jvmargs="-Xmx1000m -XX:MaxPermSize=512m